### ISSUE TITLE
TypeError for bridgeData.appToken

### ISSUE THREAD

**Issue by SteMMo33** [v0od0oChild/muzzley-bridge-node#2]
Hello Miguel,
I'm following the examples both on your book and on the doc about your library for nodejs.
Running the simple code both on Raspberry and on an Intel Platfom I always receive the same error:

    /home/pi/muzzley/node_modules/muzzley-bridge-node/lib/index.js:29
      bridgeData.appToken = account.appToken;
                          ^
TypeError: Cannot set property 'appToken' of undefined
    at Object.exports.connect (/home/pi/muzzley/node_modules/muzzley-bridge-node/lib/index.js:29:23)
    at Object.<anonymous> (/home/pi/muzzley/main.js:10:15)

Any idea?
Thanks, regards

**Comment by v0od0oChild** [comment]
Thank you for reporting the issue.
It should now be [fixed](https://github.com/v0od0oChild/muzzley-bridge-node/commit/a949212a23e9a4a10857ef2762d8bd401e1761f4)

**Comment by SteMMo33** [comment]
Yes!
Thanks a lot, updated the library by 'npm update ..' !
